### ISSUE TITLE
It doesnt work compae

### ISSUE THREAD

**Issue by mianGDZ** [sjdonado/mihorario#51]
"Error al iniciar sesion, intente de nuevo"

**Comment by sjdonado** [comment]
Hola, gracias por usar mihorarioun. Porfa presiona <kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>c</kbd>, dirigete a la pestaña: "Network" y haz click en "Fetch/XHR":
![image](https://user-images.githubusercontent.com/27580836/213765943-4acc38e5-9711-436c-bef6-c4dc13987f76.png)
Intenta iniciar sesión de nuevo y debe aparecer una petición en rojo, haz click en ella, toma ss y adjuntala acá para poder ayudar :)
